//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Mvc.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Button
    {
        public int Button_ID { get; set; }
        public string Button_OpID { get; set; }
        public string Button_Name { get; set; }
        public string Button_Operation { get; set; }
        public string Button_Magic { get; set; }
        public string Button_Describe { get; set; }
        public Nullable<System.DateTime> Create_Time { get; set; }
        public Nullable<System.DateTime> Update_Time { get; set; }
    }
}
