//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Mvc.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowActive
    {
        public int ActiveId { get; set; }
        public int FlowId { get; set; }
        public string type { get; set; }
        public string Viewfrom { get; set; }
        public string Viewto { get; set; }
        public string name { get; set; }
        public string FlowLineName { get; set; }
        public Nullable<bool> alt { get; set; }
    }
}
