//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Mvc.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowStep
    {
        public int StepId { get; set; }
        public Nullable<int> FlowId { get; set; }
        public string name { get; set; }
        public Nullable<int> Viewleft { get; set; }
        public Nullable<int> Viewtop { get; set; }
        public string type { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<bool> alt { get; set; }
        public string stepUser { get; set; }
        public string stepName { get; set; }
        public string flowNodeName { get; set; }
        public string remark { get; set; }
    }
}
