//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Mvc.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_Element
    {
        public int FEId { get; set; }
        public int FormId { get; set; }
        public Nullable<int> ElementId { get; set; }
        public string FieldIden { get; set; }
        public string ElementLable { get; set; }
        public string ElementValid { get; set; }
        public string ElementHeight { get; set; }
        public string ElementDefValue { get; set; }
        public Nullable<int> DataDictionary { get; set; }
        public string ElementFormatType { get; set; }
        public Nullable<int> ElementOrder { get; set; }
    }
}
