//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Mvc.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveInfo
    {
        public int leaveId { get; set; }
        public string leavePeople { get; set; }
        public Nullable<int> leaveDepartment { get; set; }
        public Nullable<int> leaveDays { get; set; }
        public Nullable<System.DateTime> leaveStartDate { get; set; }
        public Nullable<System.DateTime> leaveEndDate { get; set; }
        public string remark { get; set; }
    }
}
