//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Mvc.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginLog
    {
        public int Login_ID { get; set; }
        public string Login_Name { get; set; }
        public string Login_Nicker { get; set; }
        public string Login_IP { get; set; }
        public System.DateTime Login_Time { get; set; }
    }
}
