//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Mvc.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int Menu_ID { get; set; }
        public string Menu_Name { get; set; }
        public string Menu_Url { get; set; }
        public Nullable<int> Menu_ParentID { get; set; }
        public int Menu_Order { get; set; }
        public string Menu_Icon { get; set; }
        public Nullable<int> IsVisible { get; set; }
        public Nullable<System.DateTime> Create_Time { get; set; }
        public Nullable<System.DateTime> Update_Time { get; set; }
    }
}
