//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Mvc.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageID { get; set; }
        public string MessageTitle { get; set; }
        public string MessageText { get; set; }
        public int SendUser { get; set; }
        public string RecUser { get; set; }
        public System.DateTime SendTime { get; set; }
        public Nullable<System.DateTime> ExpirationTime { get; set; }
        public bool IsSendEmail { get; set; }
        public Nullable<int> SendEmailState { get; set; }
    }
}
