//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Mvc.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DDitEntities : DbContext
    {
        public DDitEntities()
            : base("name=DDitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Button> Button { get; set; }
        public virtual DbSet<Dictionary> Dictionary { get; set; }
        public virtual DbSet<DictionaryCategory> DictionaryCategory { get; set; }
        public virtual DbSet<LoginLog> LoginLog { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Menu_Button> Menu_Button { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Role_Button> Role_Button { get; set; }
        public virtual DbSet<Role_Menu> Role_Menu { get; set; }
        public virtual DbSet<SystemInfo> SystemInfo { get; set; }
        public virtual DbSet<User_Message> User_Message { get; set; }
        public virtual DbSet<User_Role> User_Role { get; set; }
        public virtual DbSet<UserInfomation> UserInfomation { get; set; }
        public virtual DbSet<ActiveCondition> ActiveCondition { get; set; }
        public virtual DbSet<FlowActive> FlowActive { get; set; }
        public virtual DbSet<FlowApprove> FlowApprove { get; set; }
        public virtual DbSet<FlowInfo> FlowInfo { get; set; }
        public virtual DbSet<FlowStep> FlowStep { get; set; }
        public virtual DbSet<WorkFlow> WorkFlow { get; set; }
        public virtual DbSet<ElementInfo> ElementInfo { get; set; }
        public virtual DbSet<Form_Element> Form_Element { get; set; }
        public virtual DbSet<FormInfo> FormInfo { get; set; }
        public virtual DbSet<LeaveInfo> LeaveInfo { get; set; }
        public virtual DbSet<New> New { get; set; }
    }
}
