//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Mvc.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role_Button
    {
        public int ID { get; set; }
        public Nullable<int> Role_ID { get; set; }
        public Nullable<int> Menu_ID { get; set; }
        public Nullable<int> Button_ID { get; set; }
    }
}
