//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Mvc.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemInfo
    {
        public int System_ID { get; set; }
        public string System_Title { get; set; }
        public string System_Version { get; set; }
        public string System_Copyright { get; set; }
        public Nullable<bool> IsValidCode { get; set; }
    }
}
